import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author T3rr3l3wis
 */
public class PlanTrip extends javax.swing.JFrame {
 Connection con;
PreparedStatement stmt;
ResultSet rs;
    /**
     * Creates new form Form4
     */
    public PlanTrip() {
        initComponents();
       fromCombo();
        toCombo();
        
       
        FromTo.setVisible(false);
        
    }
private void DoConnect( ) {
 try
       {String host="jdbc:derby://localhost:1527/TripprApp";
        String uName = "Trip";
        String uPass= "vt";
        Connection con = DriverManager.getConnection( host,uName, uPass );
String one="'"+(String)FromCombo.getSelectedItem()+"'";        
String two="'"+(String)ToCombo.getSelectedItem()+"'";
String sql="Select * from bus natural join stops where FROMSTOP="+one+"and TOSTOP="+two;
stmt=con.prepareStatement(sql);
rs=stmt.executeQuery();
FromTo.setModel(DbUtils.resultSetToTableModel(rs));

// TODO code application logic here
    }
    catch ( SQLException err ) {
System.out.println( err.getMessage( ) );
}
}
private void fromCombo()
{
    try{
        String host="jdbc:derby://localhost:1527/TripprApp";
        String uName = "Trip";
        String uPass= "vt";
        Connection con = DriverManager.getConnection( host,uName, uPass );
        String sql="Select * from stops";
        stmt=con.prepareStatement(sql);
rs=stmt.executeQuery();


  
while(rs.next()){
    int flag=0;
    String name=rs.getString("FROMSTOP");
    int i=FromCombo.getItemCount();
    while(i>0)
    {
        if(name.equals((String)FromCombo.getItemAt(i)))
          flag=1;  
        i--;
    }
    if(flag==0)   
    FromCombo.addItem(name);

}
    }
     catch ( SQLException err ) {
System.out.println( err.getMessage( ) );
}
}
private void toCombo()
{
    try{
        String host="jdbc:derby://localhost:1527/TripprApp";
        String uName = "Trip";
        String uPass= "vt";
        Connection con = DriverManager.getConnection( host,uName, uPass );
        String sql="Select * from stops";
        stmt=con.prepareStatement(sql);
rs=stmt.executeQuery();


while(rs.next()){
    int flag=0;
    String name=rs.getString("TOSTOP");
    int i=ToCombo.getItemCount();
    while(i>0)
    {
        if(name.equals((String)ToCombo.getItemAt(i)))
          flag=1;  
        i--;
    }
    if(flag==0)   
    ToCombo.addItem(name);

}
    
    }
     catch ( SQLException err ) {
System.out.println( err.getMessage( ) );
}
}

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FromTo = new javax.swing.JTable();
        FromCombo = new javax.swing.JComboBox();
        ToCombo = new javax.swing.JComboBox();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(671, 554));

        jLabel1.setText("From");

        jLabel2.setText("To");

        Search.setText("Search");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        FromTo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(FromTo);

        FromCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(Search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ToCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FromCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(Back))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(FromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Search)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
       // DoConnect();  // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        DoConnect();
       FromTo.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SearchMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
UserMenu f3 = new UserMenu();
    f3.setVisible(true);
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed
/***/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanTrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanTrip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox FromCombo;
    private javax.swing.JTable FromTo;
    private javax.swing.JButton Search;
    private javax.swing.JComboBox ToCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
